### PR TITLE
Add doubly `LinkedList` implementation to expose to scripting

### LINKED ISSUE #7194: Expose double linked list to script
There is a double linked list in godots source code (*core/list.h*).
It would be nice if that would be exposed as there are some cases where a double linked list performs way better as a vector based.
Especially when it comes to inserting/removing elements at any position except the end.

I could do some work on this, but am not sure how to handle locking and registering it (Although i could try to mirror the behavior of the Array class).
Basically exposing the list<Variant*> and list<Variant*>::Element should do the trick i guess .?
Implementing it as iterable should also work similar to how Array does it.

Additionally (and if requested i could open another issue for this) exposing the core/ring_buffer.h as queue would also be nice for queue needs.
It should perform better as a queue using a double linked list (and def. better as a vector based list) with the limitation that it has a "fixed" size and potential allocates unused memory ofc.
But there are cases where exactly this behavior is needed.

### PR DESCRIPTION
**Pull request by Xrayez**
Closes godotengine/godot#7194.
Helps godot-extended-libraries/godot-ideas#11.

Introduces `LinkedList` and `ListNode` classes, which are mostly an instantiation of built-in `List<Variant>` template/datatype.

## To-do

- [x] Port all existing `List` builtin methods.
- [x] Make `ListNode` compatible with `Variant`, done locally but submitted godotengine/godot#42060 as well.
- [x] Override `_init()`? Not sure if possible to do via C++ modules, not documented. Done by implementing `create_from` method instead, which seems to be an existing naming convention used by other methods in Godot.
- [x] Override `to_string()` for `print(list)`, should be possible with godotengine/godot#42093.
- [x] Custom iterators, done but with performance issues: godotengine/godot#42053.
- [x] Rename `LinkedList` to `List`, likely not possible as it conflicts with the built-in `List<T>` and there's no way of resolving that using namespaces either because those Godot macros assume they don't exist in C++, namely `GDCLASS` doesn't get expanded inside namespaces.
- [x] Write documentation.
- [x] Create editor icons.

---

Godot proposal: godotengine/godot-proposals#1522.

### CODE REVIEW

**Comment by Xrayez** [comment]
Tried to port existing `List::swap`, bug confirmed upstream: godotengine/godot#41981.

**Comment by Xrayez** [comment]
This is how icons look like:

goost_linked_list_and_node

**Comment by zwparchman** [comment]
Linked lists (both single and double) are almost always the wrong choice for performance. While it's true adding and removing is constant time that assumes you have a reference to the list node you want to insert after already. 

Traversing a list to find where you want to insert an item is much more expensive than inserting into the middle of an array even though they both share algorithmic complexity. This is due to a lists terrible interaction with the processor cache. There are many benchmarks scattered around the internet showing just how slow std::list is compared to std::vector. If you are pushing and popping from the front often a circular buffer is a better data structure.

An article on the subject can be found at https://baptiste-wicht.com/posts/2012/12/cpp-benchmark-vector-list-deque.html

It's worth noting that the excessive traversal cost is also payed when retrieving data from the list so using one to store often used information is often not advisable. Not only is it slow to traverse but doing so evicts other things from the cache which can cause general program performance to drop.

Given the reason to use a Linked list over an array will almost always be based on algorithmic complexity I don't think that it is unreasonable to ask for a real world use case where a list based solution performs better than an array (or circular buffer) based solution.

**Comment by Xrayez** [comment]
Yeah I guess performance is not priority for implementing such a data structure anyway, but doing so in C++ vs GDScript already provides some performance boost, but only when comparing C++ vs GDScript performance, and not list vs vector/array.

This is mostly similar/closer to graph node traversal (a [path graph](https://en.wikipedia.org/wiki/Path_graph) could be seen a list, for instance), certainly not efficient but the use cases are generally different. It's possible to nest linked lists inside other nodes/elements with the current implementation as well, making this even more flexible.

You may want to keep a general discussion going at godotengine/godot-proposals#1522 as well. 🙂

**Comment by Xrayez** [comment]
I think the current changes are complete and sufficient, the `LinkedList` API closely resembles the Godot's `List<T>` implementation, documented all methods and covered with tests, even fixed some bugs in Godot's `List` itself, some additional features can be added if needed.

**Pull request merged**
